language: node_js

node_js:
  - "stable"

addons:
  apt:
    packages:
      - google-chrome-stable

# before_install:
#   - export CHROME_BIN=/usr/bin/google-chrome

script:
  - npm test
  - npm run build
